name: Notification Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build --build-arg GITHUB_TOKEN=${{ secrets.MY_SECRET }} -t test-image .